# Generated by Django 4.2.1 on 2023-05-31 06:18

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('upload_image', models.ImageField(upload_to='media')),
                ('news_main_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('descriptions', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Latest news',
            },
        ),
    ]
