# Generated by Django 4.2.1 on 2023-05-30 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='media')),
                ('staff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_title', models.CharField(blank=True, choices=[('', 'Select Title'), ('Head of Unit', 'Head of Unit'), ('Test Facility Manager', 'Test Facility Manager'), ('Study Director', 'Study Director'), ('Project Manager', 'Project Manager'), ('Study Coordinator', 'Study Coordinator'), ('Technician', 'Technician'), ('Test Facility Coordinator', 'Test Facility Coordinator'), ('Administrative Officer', 'Administrative Officer')], max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'VCPTU Team',
            },
        ),
    ]
