# Generated by Django 4.2.1 on 2023-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcptu_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='staff_title',
            field=models.CharField(blank=True, choices=[('', 'Select Title'), ('Head of Unit', 'Head of Unit'), ('Test Facility Manager', 'Test Facility Manager'), ('Study Director', 'Study Director'), ('Project Manager', 'Project Manager'), ('Study Coordinator', 'Study Coordinator'), ('Technician', 'Technician'), ('Data Manager', 'Data Manager'), ('Test Facility Coordinator', 'Test Facility Coordinator'), ('Administrative Officer', 'Administrative Officer')], max_length=300, null=True),
        ),
    ]
