# Generated by Django 4.2.1 on 2023-06-08 12:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcptu_team', '0002_alter_teammodel_staff_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='biography',
            field=ckeditor.fields.RichTextField(default='No data'),
        ),
    ]
